export const ON_MEMBER_JOINED_ROOM = "ON_MEMBER_JOINED_ROOM"

export const ON_ADD_ITEM = "ON_ADD_ITEM"

export const ON_UPDATE_ITEM = "ON_UPDATE_ITEM"

export const ON_REMOVE_ITEM = "ON_REMOVE_ITEM"

export const ON_ITEM_CHANGE = "ON_ITEM_CHANGE"
